name: fastapi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
resources:
  requests:
    cpu: 20m
    memory: 400Mi
  limits:
    cpu: 2000m
    memory: 4000Mi
image:
  repository: test/fastapi
  tag: "1.0"
  imagePullPolicy: Never #Always #IfNotPresent #Never
  imagePullSecrets: []
service:
  type: ClusterIP
  port:
    name: http
    number: 80
    target: 80
  protocol: TCP
