apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.name }}'
  namespace: {{ .Values.namespace }}
  labels:
    app: '{{ .Values.name }}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.port.name }}
      port: {{ .Values.service.port.number }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.port.target }}
  selector:
    app: '{{ .Values.name }}'
